services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ port
      - "15672:15672" # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Redis port

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222" # NATS port

  zeromq:
    build:
      context: ./packages/zeromq
      dockerfile: Dockerfile
    container_name: zeromq
    ports:
      - "5555:5555" # ZeroMQ frontend (publishers connect here)
      - "5556:5556" # ZeroMQ backend (subscribers connect here)
